# Covering the fundamentals of tensors using TensorFlow
Shortcuts:
* ctrl+m+m will turn a cell into markdown
* shift+enter will create a new code cell
* ctrl+shift+space will show doc string of function

Topics:
* Introduction to tensors
* Getting information from tensors
* manipulating tensors
* Tensors & numpy
* using @tf.function (a way to speed up regular python functions
* using GPUs with TensorFlow (or TPUs)
* Exercises to try

Definitons:
* Scalar: a single number
* Vector: a number with director (e.g. wind speed and direction)
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional(scalar), 1-dim (vector)

# Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
# Moved Numpy import up here for convenience
import numpy as np
# There's two underscores characters before and after
print(tf.__version__)

2.5.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check number of dimensions of a tensor (ndim stand for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant ([[10.,7.],
                               [3.,2.],
                               [8.,9.]], dtype=tf.float16) #specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number dimensions of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor 
tensor = tf.constant([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]],
                       [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating tensors with tf.variable

In [ ]:
# Variable has to be capitalized
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's change one of the elements in our changeable tensor (should error)
changeable_tensor[0]=7
changeable_tensor

In [ ]:
# Correct way with .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# tf.constant does not support changing values even with .assign()

🔑 **Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal (shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (when you want to shuffle data so inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled, seed=42) #operation level seed
# If you want shuffled tensors to be in same order, have to use both

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numberical computing).

In [ ]:
numpy_A = np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# The modified tensor must have the same number of elements as the original array
# 2*3*4 = 24 and there are 24 elements in numpy_A
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors, you probably want to be aware of the following attributes:
* Shape - number of elements of each o the dimensions of a tensor - tensor.shape
* Rank - the number of tensor dimensions. scalar=rank 0, vector=rank 1, matrix=rank 2, tensor=rank n - tensor.ndim
* Axis or dimension - a particular dimension of a tensor - tensor[0], tensor [:, 1]...
* Size - total number of items in the tensor - tf.size(tensor)

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
# -1 index is python shorthand for last index
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in tensor:", tf.size(rank_4_tensor))
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor: 120


### Indexing Tensor
Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element each dimension from each index except for the final one
# Can use to colon to not grab anything
rank_4_tensor[:1,:1,:1,:], rank_4_tensor[:1,:1,:,:1]

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
 array([[[[0.],
          [0.],
          [0.],
          [0.]]]], dtype=float32)>)

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
# "..." means every axis before. Shorthand for [:,:,tf.newaxis]
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)###

**Basic operations**

`+`,`-`,`*`,`/`


In [ ]:
# You can add values to a tesnor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged unless you do e.g. tensor = + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.
Different than element-wise multiplication.

There are two rules our tensors (or matrices need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

E.g. A (3x3) matrix * a (3x2) matrix will work because inner dimensions match (3 & 3) and resulting matrix (3x2) matches outter dimensions (3 & 2):

[3]x"3" * "3"x[2] = [3]x[2]

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create a tensor (3,2) tensor
X = tf.constant([[1,2],[3,4],[5,6]])
# Create another (3,2) tensor
Y = tf.constant([[7,8],[9,10],[11,2]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11,  2]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensor of the same shape (will error)
X @ Y

InvalidArgumentError: ignored

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11,  2]], dtype=int32)>

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  13],
       [ 61,  68,  35],
       [ 95, 106,  57]], dtype=int32)>

In [ ]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(x, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  34],
       [139,  94]], dtype=int32)>

In [ ]:
# Can do the same with transpose (flip axises)
X,tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  48],
       [116,  68]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matri multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  48],
       [116,  68]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  15],
       [ 53,  67,  41],
       [ 83, 105,  67]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  13],
       [ 61,  68,  35],
       [ 95, 106,  57]], dtype=int32)>

In [ ]:
# Just wanted to see if this would work. Apparently. Yay!
!pip install autokeras
import autokeras as ak

     |████████████████████████████████| 174kB 24.0MB/s 
     |████████████████████████████████| 71kB 10.3MB/s 
  Created wheel for keras-tuner: filename=keras_tuner-1.0.2-cp37-none-any.whl size=78935 sha256=12fb5eff42affcf277dae145168d51faa48540f0456e31ffc1289ecfa4a8ad7d
  Stored in directory: /root/.cache/pip/wheels/bb/a1/8a/7c3de0efb3707a1701b36ebbfdbc4e67aedf6d4943a1f463d6
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp37-none-any.whl size=15356 sha256=40ce91cef43d2f1e707b84d8976775a6c7cea767bc1aaf9c1fb7620764c8cb23
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built keras-tuner terminaltables


In [ ]:
# check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)))

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11  2]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11  2]], shape=(2, 3), dtype=int32)
Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10  2]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axis doesn't line up, you will transpose (rather than reshape) one of the tensors to satisify the matrix multiplication rules.

### Changing the datatype of a tensor


In [ ]:
# How to check tf version
tf.__version__

'2.5.0'

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
# If you put floats in a tensor, it will bo of type float32. If you put integers, int32
C= tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# Change from floa32 to float16 (called reduced precision)
# Using 16-bit dtypes allows operations to be ran faster
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

🧾**Reference** https://www.tensorflow.org/api_docs/python/tf/math/reduce_any?hl=ko



In [ ]:
# Getting the absolute values. Turns negative numbers into positive numbers
D = tf.constant([-7,-19])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 19], dtype=int32)>

Let's go through the following forms of aggregation:


* Get the min
* Get the max
* Get the mean of a tensor
* Get the sum of a tensor



In [ ]:
# Create a random tensor with values between 0-100 of size 50
# dtype must be real or complex for variance and std dev. So, dtype=tf.float32
E = tf.constant(np.random.randint(0,100, size=50),shape=(10,5),dtype=tf.float32)
E

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[91., 68., 30., 48., 95.],
       [72., 25., 33., 70., 84.],
       [ 1., 27., 54.,  4., 10.],
       [44., 27., 88., 71., 73.],
       [95., 68., 31.,  6., 13.],
       [26.,  7., 12., 94., 58.],
       [71.,  2., 20., 91., 96.],
       [64., 57., 53., 55.,  6.],
       [53., 93., 68., 23., 38.],
       [30., 39.,  6., 29., 60.]], dtype=float32)>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([10, 5]), 2)

In [ ]:
# Find the minimum value in the tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the max value in the tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2353>

In [ ]:
# not sure why var and std require ".math"
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=886.6036>

In [ ]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.775888>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional min and max
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5311706 , 0.861194  , 0.30929685, 0.13611412, 0.36203074,
       0.41163456, 0.1469295 , 0.06661296, 0.55390525, 0.6919997 ,
       0.28603303, 0.9721898 , 0.96153307, 0.86181045, 0.6337298 ,
       0.35840178, 0.7363533 , 0.27497268, 0.3209628 , 0.60523295,
       0.9814948 , 0.72348034, 0.95994556, 0.12854326, 0.6228646 ,
       0.22936296, 0.15714204, 0.24938488, 0.8643805 , 0.46057796,
       0.8919823 , 0.8375373 , 0.24359608, 0.45765913, 0.3709607 ,
       0.38118362, 0.91896415, 0.7919122 , 0.38747358, 0.1618967 ,
       0.8078829 , 0.516958  , 0.17815995, 0.51406   , 0.681404  ,
       0.4912392 , 0.6487849 , 0.7802216 , 0.4947983 , 0.9083631 ],
      dtype=float32)>

In [ ]:
# Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9814948>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9814948>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
# Value of positional min
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.06661296>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.25256217, 0.5724336 , 0.2331121 , 0.45083058, 0.86515236,
           0.39779603, 0.86691976, 0.17403078, 0.624768  , 0.789691  ,
           0.65250254, 0.43669415, 0.88175845, 0.8033742 , 0.15008211,
           0.01929402, 0.03639221, 0.3305515 , 0.86795497, 0.3882358 ,
           0.596233  , 0.05173111, 0.1857264 , 0.5870521 , 0.785913  ,
           0.30934644, 0.3199371 , 0.22518575, 0.09190226, 0.8296913 ,
           0.9134693 , 0.7286135 , 0.54953074, 0.7523246 , 0.5018796 ,
           0.11492705, 0.16793454, 0.11469662, 0.1930846 , 0.8774396 ,
           0.5659369 , 0.7260226 , 0.4640162 , 0.46558797, 0.8604022 ,
           0.11248541, 0.42861664, 0.20789504, 0.4724797 , 0.04733193]]]]],
      dtype=float32)>

In [ ]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.25256217, 0.5724336 , 0.2331121 , 0.45083058, 0.86515236,
        0.39779603, 0.86691976, 0.17403078, 0.624768  , 0.789691  ,
        0.65250254, 0.43669415, 0.88175845, 0.8033742 , 0.15008211,
        0.01929402, 0.03639221, 0.3305515 , 0.86795497, 0.3882358 ,
        0.596233  , 0.05173111, 0.1857264 , 0.5870521 , 0.785913  ,
        0.30934644, 0.3199371 , 0.22518575, 0.09190226, 0.8296913 ,
        0.9134693 , 0.7286135 , 0.54953074, 0.7523246 , 0.5018796 ,
        0.11492705, 0.16793454, 0.11469662, 0.1930846 , 0.8774396 ,
        0.5659369 , 0.7260226 , 0.4640162 , 0.46558797, 0.8604022 ,
        0.11248541, 0.42861664, 0.20789504, 0.4724797 , 0.04733193],
       dtype=float32)>, 1)

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# One-hot encode our list of indices (incides, depth)
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yeah baby!", off_value="grr")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yeah baby!', b'grr', b'grr', b'grr'],
       [b'grr', b'Yeah baby!', b'grr', b'grr'],
       [b'grr', b'grr', b'Yeah baby!', b'grr'],
       [b'grr', b'grr', b'grr', b'Yeah baby!']], dtype=object)>

### Squaring ,log, and square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root (sqrt doesn't work on int32)
# Use tf.cast to change dtype
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Find the log (also doesn't work on int32)
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

🔑 Note: One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing)

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a numpy array
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
# Deprecated. Will give a warning
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
# Get all physical devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# Get physical devices of type GPU
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# Enable GPU in Colab:
# Runtime > Change runtime type > Hardware Accelerator > GPU

In [ ]:
# Google uses Nvidia GPUs. Can use !nvidia-smi command to see more info about the GPU
!nvidia-smi

Mon Jun 21 15:24:16 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 **Note**: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible